@extends('layouts.app')

@section('title', 'Liên hệ')

@section('content')
    <section class="page-hero"><div class="container"><div class="eyebrow mb-3">Liên hệ</div><h1 class="display-5 fw-bold mb-3">Kết nối với Valora</h1><p class="lead mb-0 col-lg-7">Gửi câu hỏi về cơ hội nghề nghiệp hoặc quy trình ứng tuyển cho đội ngũ của chúng tôi.</p></div></section>
    <section class="section-space section-muted"><div class="container"><div class="row g-5">
        <div class="col-lg-5" data-reveal><div class="eyebrow mb-3">Hỗ trợ ứng viên</div><h2 class="section-heading mb-4">Chúng tôi sẵn sàng lắng nghe</h2><p class="text-muted-valora mb-5">Để đảm bảo chính xác, địa chỉ, số điện thoại và email chính thức sẽ được cập nhật sau khi doanh nghiệp cung cấp dữ liệu xác nhận.</p>@foreach ([['clock-3', 'Thời gian phản hồi', 'Đội ngũ tuyển dụng sẽ phản hồi trong thời gian phù hợp.'], ['shield-check', 'Bảo mật thông tin', 'Thông tin liên hệ chỉ được dùng để xử lý nội dung bạn gửi.']] as [$icon, $title, $copy])<div class="d-flex gap-3 mb-4"><div class="feature-icon flex-shrink-0"><i data-lucide="{{ $icon }}"></i></div><div><h3 class="h6 fw-bold">{{ $title }}</h3><p class="text-muted-valora mb-0">{{ $copy }}</p></div></div>@endforeach</div>
        <div class="col-lg-7"><div class="form-panel"><h2 class="h4 fw-bold mb-4">Gửi lời nhắn</h2><x-flash /><form method="POST" action="{{ route('contact.store') }}">@csrf<div class="row g-4"><div class="col-md-6"><label class="form-label" for="full_name">Họ và tên <span class="text-danger">*</span></label><input class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name" value="{{ old('full_name') }}" required>@error('full_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="email">Email <span class="text-danger">*</span></label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="phone">Số điện thoại</label><input class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" value="{{ old('phone') }}">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label" for="message">Nội dung <span class="text-danger">*</span></label><textarea class="form-control @error('message') is-invalid @enderror" id="message" name="message" rows="7" required>{{ old('message') }}</textarea>@error('message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><button class="btn btn-accent btn-icon mt-4" type="submit"><i data-lucide="send" class="icon-sm"></i>Gửi liên hệ</button></form></div></div>
    </div></div></section>
@endsection
