[providers]
providers = ["php", "node"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[variables]
NIXPACKS_PHP_ROOT_DIR = "public"