@extends('layouts.admin')

@section('title', $application->full_name)
@section('page_title', 'Chi tiết ứng viên')

@section('content')
    <div class="d-flex flex-column flex-lg-row align-items-lg-start justify-content-between gap-3 mb-4"><div><a class="small btn-icon" href="{{ route('admin.applications.index') }}"><i data-lucide="arrow-left" class="icon-sm"></i>Danh sách ứng viên</a><h1 class="h3 fw-bold mt-2 mb-1">{{ $application->full_name }}</h1><p class="text-muted-valora mb-0">Ứng tuyển {{ $application->job->title }}</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary btn-icon" href="{{ route('admin.applications.cv.view', $application) }}" target="_blank"><i data-lucide="file-search" class="icon-sm"></i>Xem CV</a><a class="btn btn-primary btn-icon" href="{{ route('admin.applications.cv.download', $application) }}"><i data-lucide="download" class="icon-sm"></i>Tải CV</a></div></div>
    <div class="row g-4"><div class="col-xl-8"><div class="admin-card p-3 p-lg-4 mb-4"><h2 class="h5 fw-bold mb-4">Thông tin ứng viên</h2><dl class="row g-3 mb-0"><dt class="col-sm-4 text-muted-valora fw-normal">Họ và tên</dt><dd class="col-sm-8 fw-semibold">{{ $application->full_name }}</dd><dt class="col-sm-4 text-muted-valora fw-normal">Email</dt><dd class="col-sm-8"><a href="mailto:{{ $application->email }}">{{ $application->email }}</a></dd><dt class="col-sm-4 text-muted-valora fw-normal">Số điện thoại</dt><dd class="col-sm-8">{{ $application->phone }}</dd><dt class="col-sm-4 text-muted-valora fw-normal">Địa chỉ</dt><dd class="col-sm-8">{{ $application->address ?: 'Không cung cấp' }}</dd><dt class="col-sm-4 text-muted-valora fw-normal">Ngày ứng tuyển</dt><dd class="col-sm-8">{{ $application->created_at->format('d/m/Y H:i') }}</dd></dl></div><div class="admin-card p-3 p-lg-4"><h2 class="h5 fw-bold mb-3">Thư giới thiệu</h2><div class="prose-block">{{ $application->cover_letter ?: 'Ứng viên không gửi thư giới thiệu.' }}</div></div></div>
        <div class="col-xl-4"><div class="admin-card p-3 p-lg-4 mb-4"><h2 class="h5 fw-bold mb-4">Cập nhật trạng thái</h2><form method="POST" action="{{ route('admin.applications.status', $application) }}">@csrf @method('PATCH')<label class="form-label" for="status">Trạng thái hồ sơ</label><select class="form-select mb-3" id="status" name="status">@foreach ($statuses as $value => $label)<option value="{{ $value }}" @selected($application->status === $value)>{{ $label }}</option>@endforeach</select><button class="btn btn-primary btn-icon w-100" type="submit"><i data-lucide="save" class="icon-sm"></i>Lưu trạng thái</button></form></div><div class="admin-card p-3 p-lg-4 mb-4"><h2 class="h5 fw-bold mb-3">Vị trí ứng tuyển</h2><a class="fw-semibold" href="{{ route('admin.jobs.show', $application->job) }}">{{ $application->job->title }}</a><div class="small text-muted-valora mt-2">{{ $application->job->department->name }} · {{ $application->job->location }}</div></div><div class="admin-card p-3"><button class="btn btn-outline-danger btn-icon w-100" type="button" data-bs-toggle="modal" data-bs-target="#deleteApplicationModal"><i data-lucide="trash-2" class="icon-sm"></i>Xóa hồ sơ</button></div></div>
    </div>
    <div class="modal fade" id="deleteApplicationModal" tabindex="-1" aria-labelledby="deleteApplicationLabel" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="deleteApplicationLabel">Xóa hồ sơ ứng viên?</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body">Hồ sơ và CV đính kèm sẽ bị xóa vĩnh viễn.</div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Hủy</button><form method="POST" action="{{ route('admin.applications.destroy', $application) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Xác nhận xóa</button></form></div></div></div></div>
@endsection
