@php($editing = isset($job))
<div class="row g-4">
    <div class="col-lg-8"><div class="admin-card p-3 p-lg-4"><h2 class="h5 fw-bold mb-4">Nội dung vị trí</h2><div class="row g-3">
        <div class="col-md-8"><label class="form-label" for="title">Tên vị trí *</label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title', $job->title ?? '') }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-4"><label class="form-label" for="department_id">Phòng ban *</label><select class="form-select @error('department_id') is-invalid @enderror" id="department_id" name="department_id" required><option value="">Chọn phòng ban</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id', $job->department_id ?? '') === (string) $department->id)>{{ $department->name }}</option>@endforeach</select>@error('department_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $job->slug ?? '') }}" placeholder="Tự tạo từ tên vị trí nếu để trống">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="description">Mô tả công việc *</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="8" required>{{ old('description', $job->description ?? '') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="requirements">Yêu cầu ứng viên *</label><textarea class="form-control @error('requirements') is-invalid @enderror" id="requirements" name="requirements" rows="8" required>{{ old('requirements', $job->requirements ?? '') }}</textarea>@error('requirements')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="benefits">Quyền lợi *</label><textarea class="form-control @error('benefits') is-invalid @enderror" id="benefits" name="benefits" rows="8" required>{{ old('benefits', $job->benefits ?? '') }}</textarea>@error('benefits')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="col-lg-4"><div class="admin-card p-3 p-lg-4 mb-4"><h2 class="h5 fw-bold mb-4">Thông tin tuyển dụng</h2><div class="d-grid gap-3">
        <div><label class="form-label" for="location">Địa điểm *</label><input class="form-control @error('location') is-invalid @enderror" id="location" name="location" value="{{ old('location', $job->location ?? '') }}" required>@error('location')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div><label class="form-label" for="employment_type">Loại hình *</label><select class="form-select @error('employment_type') is-invalid @enderror" id="employment_type" name="employment_type" required>@foreach ($employmentTypes as $value => $label)<option value="{{ $value }}" @selected(old('employment_type', $job->employment_type ?? 'full_time') === $value)>{{ $label }}</option>@endforeach</select>@error('employment_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div><label class="form-label" for="salary">Mức lương</label><input class="form-control @error('salary') is-invalid @enderror" id="salary" name="salary" value="{{ old('salary', $job->salary ?? '') }}" placeholder="Ví dụ: 12 - 18 triệu">@error('salary')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div><label class="form-label" for="experience">Kinh nghiệm</label><input class="form-control @error('experience') is-invalid @enderror" id="experience" name="experience" value="{{ old('experience', $job->experience ?? '') }}" placeholder="Ví dụ: 1 - 2 năm">@error('experience')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div><label class="form-label" for="deadline">Hạn ứng tuyển</label><input class="form-control @error('deadline') is-invalid @enderror" id="deadline" name="deadline" type="date" value="{{ old('deadline', isset($job) ? $job->deadline?->format('Y-m-d') : '') }}">@error('deadline')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div><label class="form-label" for="status">Trạng thái *</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach ($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', $job->status ?? 'draft') === $value)>{{ $label }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="form-check form-switch"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" id="is_featured" name="is_featured" type="checkbox" value="1" @checked(old('is_featured', $job->is_featured ?? false))><label class="form-check-label" for="is_featured">Vị trí nổi bật</label></div>
    </div></div><div class="admin-card p-3"><button class="btn btn-primary btn-icon w-100" type="submit"><i data-lucide="save" class="icon-sm"></i>{{ $editing ? 'Lưu thay đổi' : 'Tạo việc làm' }}</button><a class="btn btn-outline-secondary w-100 mt-2" href="{{ route('admin.jobs.index') }}">Hủy</a></div></div>
</div>
