@extends('layouts.admin')

@section('title', $job->title)
@section('page_title', 'Chi tiết việc làm')

@section('content')
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-start gap-3 mb-4">
        <div><a class="small btn-icon" href="{{ route('admin.jobs.index') }}"><i data-lucide="arrow-left" class="icon-sm"></i>Danh sách việc làm</a><h1 class="h3 fw-bold mt-2 mb-1">{{ $job->title }}</h1><p class="text-muted-valora mb-0">{{ $job->department->name }} · {{ $job->location }}</p></div>
        <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary btn-icon" href="{{ route('admin.jobs.edit', $job) }}"><i data-lucide="pencil" class="icon-sm"></i>Chỉnh sửa</a>@if ($job->status !== 'published')<form method="POST" action="{{ route('admin.jobs.publish', $job) }}">@csrf @method('PATCH')<button class="btn btn-primary btn-icon"><i data-lucide="radio-tower" class="icon-sm"></i>Xuất bản</button></form>@endif @if ($job->status !== 'closed')<form method="POST" action="{{ route('admin.jobs.close', $job) }}">@csrf @method('PATCH')<button class="btn btn-outline-warning btn-icon"><i data-lucide="circle-stop" class="icon-sm"></i>Đóng tuyển</button></form>@endif</div>
    </div>
    <div class="row g-4">
        <div class="col-xl-8"><div class="admin-card p-3 p-lg-4">@foreach ([['Mô tả công việc', $job->description], ['Yêu cầu ứng viên', $job->requirements], ['Quyền lợi', $job->benefits]] as [$heading, $copy])<section class="mb-5"><h2 class="h5 fw-bold mb-3">{{ $heading }}</h2><div class="prose-block">{{ $copy }}</div></section>@endforeach</div></div>
        <div class="col-xl-4"><div class="admin-card p-3 p-lg-4 mb-4"><h2 class="h5 fw-bold mb-4">Thông tin</h2><dl class="row g-3 mb-0"><dt class="col-5 text-muted-valora fw-normal">Trạng thái</dt><dd class="col-7 fw-semibold">{{ $job->statusLabel() }}</dd><dt class="col-5 text-muted-valora fw-normal">Loại hình</dt><dd class="col-7 fw-semibold">{{ $job->employmentTypeLabel() }}</dd><dt class="col-5 text-muted-valora fw-normal">Mức lương</dt><dd class="col-7 fw-semibold">{{ $job->salary ?: 'Thỏa thuận' }}</dd><dt class="col-5 text-muted-valora fw-normal">Kinh nghiệm</dt><dd class="col-7 fw-semibold">{{ $job->experience ?: 'Không yêu cầu' }}</dd><dt class="col-5 text-muted-valora fw-normal">Deadline</dt><dd class="col-7 fw-semibold">{{ $job->deadline?->format('d/m/Y') ?: 'Không giới hạn' }}</dd><dt class="col-5 text-muted-valora fw-normal">Hồ sơ</dt><dd class="col-7 fw-semibold">{{ $job->applications_count }}</dd><dt class="col-5 text-muted-valora fw-normal">Người tạo</dt><dd class="col-7 fw-semibold">{{ $job->creator?->name ?: 'Hệ thống' }}</dd></dl></div>
        <div class="admin-card p-3"><a class="btn btn-outline-primary btn-icon w-100 mb-2" href="{{ route('careers.show', $job) }}" target="_blank"><i data-lucide="external-link" class="icon-sm"></i>Xem trang public</a><button class="btn btn-outline-danger btn-icon w-100" type="button" data-bs-toggle="modal" data-bs-target="#deleteJobModal"><i data-lucide="trash-2" class="icon-sm"></i>Xóa việc làm</button></div></div>
    </div>
    <div class="modal fade" id="deleteJobModal" tabindex="-1" aria-labelledby="deleteJobLabel" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="deleteJobLabel">Xóa vị trí tuyển dụng?</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body">Thao tác này sẽ xóa vị trí và toàn bộ hồ sơ, CV liên quan. Không thể hoàn tác.</div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Hủy</button><form method="POST" action="{{ route('admin.jobs.destroy', $job) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Xác nhận xóa</button></form></div></div></div></div>
@endsection
